version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: solar-system-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: solar-system-backend-test
    depends_on:
      - backend
    command: ["./mvnw", "test"]
    environment:
      - SPRING_PROFILES_ACTIVE=docker
