name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      env:
        SOLAREDGE_API_KEY: ${{ secrets.SOLAREDGE_API_KEY }}
        SOLAREDGE_SITE_ID: ${{ secrets.SOLAREDGE_SITE_ID }}
    
    - name: Run Tests
      run: mvn test
      env:
        SOLAREDGE_API_KEY: ${{ secrets.SOLAREDGE_API_KEY }}
        SOLAREDGE_SITE_ID: ${{ secrets.SOLAREDGE_SITE_ID }}

name: CI - Backend Tests

on:
  pull_request:
    branches:
      - main
      - clean-architecture

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SOLAREDGE_SITE_ID: dummy
      SOLAREDGE_API_KEY: dummy
      SOLAREDGE_API_URL: https://api.solaredge.com
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Run backend tests in Docker
        run: |
          docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit 