spring:
  config:
    import: optional:file:.env

solaredge:
  api:
    api-key: ${SOLAREDGE_API_KEY:dev_api_key}  # Read from env or use default
    site-id: ${SOLAREDGE_SITE_ID:dev_site_id}  # Read from env or use default

logging:
  file:
    name: logs\solar-system-monitoring.log
  level:
    root: INFO
    solar_system_monitoring: DEBUG

server:
  port: ${SERVER_PORT:8080} 