name: Backend CI

on:
  pull_request:
    paths:
      - 'backend/**'
  push:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Run tests
        env:
          SPRING_PROFILES_ACTIVE: test
          SOLAREDGE_API_KEY: dummy
          SOLAREDGE_SITE_ID: dummy
          SOLAREDGE_API_URL: https://example.com
        run: ./mvnw -B -ntp test

