name: Backend Tests

on:
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/backend-tests.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Run Tests
        run: ./mvnw test
