name: Backend Tests

on:
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/backend-tests.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Run Tests
        run: ./mvnw test

      - name: Report Status
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const conclusion = context.job.status;
            await github.rest.checks.create({
              ...context.repo,
              name: 'Backend Tests',
              head_sha: context.sha,
              status: 'completed',
              conclusion: conclusion.toLowerCase(),
              output: {
                title: 'Test Results',
                summary: `Backend tests ${conclusion}`
              }
            });
